import Image from "next/image";
import Link from "next/link";
import type { Dictionary } from "@/lib/i18n/dictionaries/types";

// The paper guide that ships inside the box. The leaflet artwork is English
// only (text baked into the raster), so every instruction is also rendered
// as live, translatable text below it — the images are the "real paper"
// preview, the steps are the source of truth. Assets are generated by
// scripts/generate-guide-assets.ts.
//
// Server component, zero client JS: the mobile carousel is plain CSS
// scroll-snap.

const OUTSIDE_PANELS = [
  { src: "/guide/outside-1.webp", width: 417, height: 468 },
  { src: "/guide/outside-2.webp", width: 498, height: 468 },
  { src: "/guide/outside-3.webp", width: 445, height: 468 },
];
const INSIDE_PANELS = [
  { src: "/guide/inside-1.webp", width: 450, height: 484 },
  { src: "/guide/inside-2.webp", width: 490, height: 484 },
  { src: "/guide/inside-3.webp", width: 448, height: 484 },
];
const PANELS = [...OUTSIDE_PANELS, ...INSIDE_PANELS];

function InfoIcon({ className }: { className?: string }) {
  return (
    <svg
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth={1.8}
      strokeLinecap="round"
      strokeLinejoin="round"
      className={className}
    >
      <circle cx="12" cy="12" r="9" />
      <path d="M12 11v5" />
      <circle cx="12" cy="7.8" r="0.6" fill="currentColor" />
    </svg>
  );
}

function BulbIcon({ className }: { className?: string }) {
  return (
    <svg
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth={1.8}
      strokeLinecap="round"
      strokeLinejoin="round"
      className={className}
    >
      <path d="M9 18h6M10 21h4" />
      <path d="M12 3a6 6 0 0 0-3.5 10.9c.6.5 1 1.2 1 2V16h5v-.1c0-.8.4-1.5 1-2A6 6 0 0 0 12 3Z" />
    </svg>
  );
}

export function GuideSection({
  t,
  variant = "section",
}: {
  t: Dictionary["guide"];
  /** "section" is the homepage band; "page" is the standalone /guide. */
  variant?: "section" | "page";
}) {
  const isPage = variant === "page";

  return (
    <div className="mx-auto max-w-5xl px-6">
      <div className="text-center">
        <span className="text-xs font-semibold uppercase tracking-wide text-brand-600">
          {t.kicker}
        </span>
        {isPage ? (
          <h1 className="mt-4 text-3xl font-semibold text-balance text-brand-900 sm:text-4xl">
            {t.pageTitle}
          </h1>
        ) : (
          <h2 className="mt-4 text-3xl font-semibold text-balance text-brand-900 sm:text-4xl">
            {t.heading}
          </h2>
        )}
        <p className="mx-auto mt-4 max-w-xl text-balance text-slate-500">
          {isPage ? t.pageSubtitle : t.subtitle}
        </p>
      </div>

      {/* Desktop: the open leaflet, outside then inside, stacked like paper on a desk. */}
      <div className="mt-12 hidden flex-col gap-8 md:flex">
        <figure>
          <Image
            src="/guide/outside.webp"
            alt={t.outsideAlt}
            width={1346}
            height={468}
            sizes="(min-width: 1024px) 1024px, 90vw"
            unoptimized
            loading={isPage ? "eager" : "lazy"}
            className="fade-up w-full -rotate-[0.6deg] drop-shadow-[0_18px_24px_rgba(15,23,42,0.18)]"
          />
          <figcaption className="mt-3 text-center text-xs font-medium uppercase tracking-wide text-slate-400">
            {t.outsideLabel}
          </figcaption>
        </figure>
        <figure>
          <Image
            src="/guide/inside.webp"
            alt={t.insideAlt}
            width={1374}
            height={484}
            unoptimized
            sizes="(min-width: 1024px) 1024px, 90vw"
            className="fade-up w-full rotate-[0.6deg] drop-shadow-[0_18px_24px_rgba(15,23,42,0.18)]"
            style={{ animationDelay: "120ms" }}
          />
          <figcaption className="mt-3 text-center text-xs font-medium uppercase tracking-wide text-slate-400">
            {t.insideLabel}
          </figcaption>
        </figure>
      </div>

      {/* Mobile: one panel at a time, swipe through all six. Breaks out of the
          page gutter so the next panel peeks in as a swipe affordance. */}
      <div className="mt-10 md:hidden">
        <div
          className="-mx-6 flex snap-x snap-mandatory gap-4 overflow-x-auto px-6 pb-10 pt-2 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden"
          role="group"
          aria-roledescription="carousel"
          aria-label={t.heading}
          tabIndex={0}
        >
          {PANELS.map((panel, i) => (
            <Image
              key={panel.src}
              src={panel.src}
              alt={t.panelAlts[i]}
              width={panel.width}
              height={panel.height}
              sizes="85vw"
              unoptimized
              className="h-auto w-[82%] max-w-sm shrink-0 snap-center drop-shadow-[0_12px_16px_rgba(15,23,42,0.18)]"
            />
          ))}
        </div>
        <p className="-mt-4 text-center text-xs text-slate-400">{t.swipeHint} →</p>
      </div>

      {/* The same content as live text: translatable, searchable, accessible. */}
      <div className="mt-14">
        <h3 className="sr-only">{t.stepsHeading}</h3>
        <ol className="grid grid-cols-1 gap-4 md:grid-cols-3">
          {t.steps.map((step, i) => (
            <li
              key={step.title}
              className="rounded-3xl bg-slate-50 p-6 shadow-[0_2px_20px_-6px_rgba(15,23,42,0.10)]"
            >
              <span className="flex h-9 w-9 items-center justify-center rounded-full bg-brand-900 text-sm font-semibold text-white">
                {i + 1}
              </span>
              <p className="mt-4 font-semibold text-brand-900">{step.title}</p>
              <p className="mt-1.5 text-sm leading-relaxed text-slate-500">{step.body}</p>
            </li>
          ))}
        </ol>

        <div className="mt-4 grid grid-cols-1 gap-4 md:grid-cols-2">
          <p className="flex items-start gap-3 rounded-3xl bg-brand-50/70 p-5 text-sm leading-relaxed text-brand-900">
            <InfoIcon className="mt-0.5 h-5 w-5 shrink-0 text-brand-600" />
            {t.androidNote}
          </p>
          <p className="flex items-start gap-3 rounded-3xl bg-accent-500/10 p-5 text-sm leading-relaxed text-brand-900">
            <BulbIcon className="mt-0.5 h-5 w-5 shrink-0 text-accent-500" />
            {t.proTip}
          </p>
        </div>

        <p className="mt-6 text-center text-sm font-medium text-brand-700">{t.noAppNeeded}</p>

        {!isPage && (
          <div className="mt-6 flex justify-center">
            <Link
              href="/guide"
              className="rounded-full border border-slate-200 px-5 py-2.5 text-sm font-semibold text-brand-900 transition hover:bg-slate-50"
            >
              {t.viewFullGuide}
            </Link>
          </div>
        )}
      </div>
    </div>
  );
}
